FROM docker.elastic.co/beats/metricbeat:7.16.3
COPY metricbeat.yml /usr/share/metricbeat/metricbeat.yml
COPY entrypoint.sh /usr/local/bin/entrypoint.sh
#RUN chmod +x /usr/local/bin/entrypoint.sh 
RUN chmod go-w /usr/share/metricbeat/metricbeat.yml

#ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
