version: "3.4"

services:
  MShop.catalago:
    container_name: catalagoDb
    hostname: catalagoDb
    image: mariadb:10.6.3
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: "mshop"
      MYSQL_USER: "mshop"
      MYSQL_PASSWORD: "mshop"
      MYSQL_DATABASE: "mshop"
  
  MShop.Redis:
    container_name: redis
    hostname: redis
    image: redis
    ports:
      - "8379:6379" 