version: "3.4"

services:
  app:
    container_name: adm_videos_app
    image: marckvaldo/mshop.api.product:V-33
    #image: ""
    restart: unless-stopped
    ports:
      - 5000:80
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - MShop.catalago.dev
      - Mshop.Rabbitmq.dev
      - Mshop.Filebeat.dev
    labels:
      filebeat_collector: true
      decode_log_event_to_json_object: true
    networks:
      - app-catalago

  MShop.catalago.dev:
    container_name: catalagoDb-dev
    hostname: catalagoDb-dev
    image: mariadb:10.6.3
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "mshop"
      MYSQL_USER: "mshop"
      MYSQL_PASSWORD: "mshop"
      MYSQL_DATABASE: "mshop"
    networks:
      - app-catalago
  #MShop.Redis.dev:
    #container_name: redis-dev
    #hostname: redis-dev
    #image: redis
    #ports:
    #  - "8378:6379" 
    #networks:
    #  - app-catalago
  Mshop.Rabbitmq.dev:
    container_name: rabbitmq-dev
    image: rabbitmq:3-management
    hostname: rabbitmq-dev
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=123456
      - RABBITMQ_DEFAULT_VHOST=catalago
    ports:
      - 15672:15672 #potaHost : Porta Container
      - 5672:5672
    networks:
      - app-catalago

  Mshop.Filebeat.dev:
    container_name: filebeat-dev
    image: docker.elastic.co/beats/filebeat:8.10.2
    command: filebeat -e -strict.perms=false
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro                    # Docker logs
      - /var/run/docker.sock:/var/run/docker.sock:ro                                # Additional information about containers
      - .docker/filebeat/filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:ro    # Configuration file
      - .docker/filebeat:/usr/share/filebeat/data:rw                                # Persistence data
    user: root                                                                      # Allow access to log files and docker.sock
    restart: on-failure
    networks:
      - app-catalago

networks:
  app-catalago:
    driver: bridge