version: "3.4"

services:
  Mshop.Rabbitmq:
    container_name: catalago_rabbitmq
    image: rabbitmq:3-management
    hostname: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=123456
      - RABBITMQ_DEFAULT_VHOST="catalago"
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - app-catalago

networks:
  app-catalago:
    driver: bridge